In [77]:
import numpy as np
np.__version__

'1.21.5'

In [4]:
np.full((3,5),3.14159265358979323) #創建一個3x5陣列: 所有元素都是同一個數字pi的近似

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [6]:
np.arange(0,20,2)  #創建一個等差數列陣列:從0開始,不足20終止

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.linspace(0,1,5)# 0~1  五個等分割點，包含兩端點

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.random.randint(0,10,size=(3,2) ) #3x2矩陣中都是 0~10隨機整數之間

array([[4, 7],
       [6, 8],
       [8, 1]])

In [23]:
np.random.seed(0) #固定隨機種子
np.random.random(size=(3,2))

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [24]:
np.random.normal(size=(3,2) )

array([[ 0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351]])

In [171]:
np.eye(3).shape

(3, 3)

In [30]:
np.zeros(11,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [31]:
np.zeros(11,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [28]:
np.zeros(10,dtype='int32')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
x1=np.random.randint(0,10,(3,4),dtype=np.int16)

# 單維度切片

In [172]:

data1=np.array([ [-1,-5,2,3] ]) #記得雙中括號才是1x4

In [173]:
data1.shape

(1, 4)

In [133]:
data1[1:3]

array([-5,  2])

# 多維度切片

In [135]:
data = np.array([
    [0,1,2],
    [10,-5,3],
    [2,6,2],
    [2,1,0]
])
print("形狀為{},大小為{}".format( data.shape,data.size))

形狀為(4, 3),大小為12


In [136]:
# 注意不要有小括號
data[1:3,0:2] 

array([[10, -5],
       [ 2,  6]])

In [140]:
data[0:2,1]
data[0:2,1].dtype

dtype('int32')

In [141]:
data=np.array(
[
    [
        [2,1,3],[1,2,3]
    ],
    [
        [0,2,1],[8,9,10]
    ]
])

In [143]:
data.shape

(2, 2, 3)

In [144]:
data.size

12

In [145]:
data[0,...]

array([[2, 1, 3],
       [1, 2, 3]])

In [146]:
data[...,1:3] 

array([[[ 1,  3],
        [ 2,  3]],

       [[ 2,  1],
        [ 9, 10]]])

In [148]:
data=np.full((4,5,6),3.14)

# 合併 stack 
# 將數個多維陣列，合併成一個

In [181]:
data1=np.array([
    [3,4,5,6,7],
    [1,2,3,4,5]
])  #2x5

In [182]:
data2=np.array(
    [
        [11,12,13,14,15],
        [21,22,23,24,25]
    ]) #2x5

# 合併第一個維度

In [183]:
result1=np.vstack( (data1,data2) )

result1

array([[ 3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

# 合併第二個維度

In [184]:
result2 = np.hstack( (data1,data2) )
result2

array([[ 3,  4,  5,  6,  7, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25]])

# 合併三個陣列

In [186]:
arr1=np.array([
    [1,2,3],
    [4,5,6]    
]
)

In [188]:
arr2=np.array([
    [7,8,9],
    [10,11,12]
])

In [192]:
arr3=np.array([
    [13,14],
    [15,16]
])

In [195]:
result3 = np.hstack( (arr1,arr2,arr3) ) 
result3

array([[ 1,  2,  3,  7,  8,  9, 13, 14],
       [ 4,  5,  6, 10, 11, 12, 15, 16]])

# 切割資料

In [197]:
# 準備測試資料
arr=np.array(
[
    [2,4,6,8,10,12],
    [1,3,5,7,9,11]
    
])
arr
#2x6

array([[ 2,  4,  6,  8, 10, 12],
       [ 1,  3,  5,  7,  9, 11]])

In [198]:
arr.shape

(2, 6)

In [199]:
#根據第一個維度切割
result = np.vsplit(arr,2)

In [200]:
result

[array([[ 2,  4,  6,  8, 10, 12]]), array([[ 1,  3,  5,  7,  9, 11]])]

In [204]:
 np.vsplit(arr,2)

[array([[ 2,  4,  6,  8, 10, 12]]), array([[ 1,  3,  5,  7,  9, 11]])]

In [208]:
# 準備測試資料
arr=np.array(
[
    [2,4,6,8,10,12],
    [1,3,5,7,9,11]
    
])
arr
#2x6

array([[ 2,  4,  6,  8, 10, 12],
       [ 1,  3,  5,  7,  9, 11]])

In [210]:
#根據第二個維度切割
np.hsplit(arr,2) #切成兩個2x3的陣列

[array([[2, 4, 6],
        [1, 3, 5]]),
 array([[ 8, 10, 12],
        [ 7,  9, 11]])]

In [211]:
#根據第二個維度切割
np.hsplit(arr,3) #切成三個2x2的陣列

[array([[2, 4],
        [1, 3]]),
 array([[6, 8],
        [5, 7]]),
 array([[10, 12],
        [ 9, 11]])]

In [ ]:
# 延伸
