In [2]:
import numpy as np

In [4]:
data=np.array([
    [2,4,1],
    [1,5,0]
])
data

array([[2, 4, 1],
       [1, 5, 0]])

In [5]:
data.shape

(2, 3)

In [8]:
data.T
# 轉置資料

array([[2, 1],
       [4, 5],
       [1, 0]])

In [9]:
data.T.shape

(3, 2)

In [10]:
data=np.array(
[
    [
        [2,1,3],[1,2,3]
    ],
    [
        [0,2,1],[8,9,10]
    ]
])

In [11]:
data

array([[[ 2,  1,  3],
        [ 1,  2,  3]],

       [[ 0,  2,  1],
        [ 8,  9, 10]]])

In [12]:
newdata=data.ravel()

In [13]:
newdata

array([ 2,  1,  3,  1,  2,  3,  0,  2,  1,  8,  9, 10])

In [14]:
data.shape
# 2x2x3=12

(2, 2, 3)

In [15]:
data.reshape(3,4)
# 3x4=12

array([[ 2,  1,  3,  1],
       [ 2,  3,  0,  2],
       [ 1,  8,  9, 10]])

In [16]:
data.reshape(1,2,6)


array([[[ 2,  1,  3,  1,  2,  3],
        [ 0,  2,  1,  8,  9, 10]]])

In [17]:
data.reshape(1,2,4)


ValueError: cannot reshape array of size 12 into shape (1,2,4)

In [18]:
# 初始化資料
data =np.zeros(18)
data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [20]:
data =np.zeros(18).reshape(3,6)
data

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
data =np.zeros(18).reshape(3,2,3)
data

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
data=np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
data.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])